### ISSUE TITLE
Plug-in failing due to missing files

### ISSUE THREAD

**Issue by EdwinFRL** [retug/SectionCutter#1]
Build error: Properties/AssemblyInfo.cs missing
When adding this file to the project, no build errors occur

"Plug-in failed!" error message when running the plug-in in Etabs. This is solved when adding the following files to the same directory as SectionCutter.dll:
- LiveCharts.WinForms.dll
- LiveCharts.Wpf.dll

**Comment by retug** [comment]
I have added these (2) .dll files in the github repo, hopefully this resolves the issue.
If you have a second, give a try on your end.

Thanks!

**Comment by retug** [comment]
hopefully resolved, see youtube for demonstration.
https://www.youtube.com/watch?v=CUDt8zJYAoc
