### ISSUE TITLE
Plugin Installation

### ISSUE THREAD

**Issue by AArman986** [retug/SectionCutter#10]
Good day,
                I tried installing your plugin as I saw it on the ETABS website but it stated installation failed. ETABS v21.2.0. Any help. Thanks

**Comment by retug** [comment]
Hi,

I just added (2) additional .dll files that I believe need to be added for proper install. I also updated the install instructions, let me know if this resolves the issue.

**Comment by AArman986** [comment]
Thanks. Downloaded the added dll files into same folder (I placed all files dlls and other in same folder. But still get error plugin failed. I only joined the community to correspond with you on plugin so I'm not sure if there is some other software your plugin requires to run.

**Comment by retug** [comment]
Interesting, can you provide some screenshots of your error? Maybe we do a screen share so I can see the issue.
Feel free to shoot me an email.

Thank you for your patience, sorry for the inconvenience! First time distributing an ETABs addin.

**Comment by AArman986** [comment]
See photos
![image](https://github.com/retug/SectionCutter/assets/158470435/5d8540b5-9514-445b-bc8b-ac31f2d94b9b)
![image](https://github.com/retug/SectionCutter/assets/158470435/f2dd8404-5a42-49ee-9459-6906b11d81cf)
![image](https://github.com/retug/SectionCutter/assets/158470435/610c9daa-e5d1-4b36-bf2a-f4198d938f87)

**Comment by retug** [comment]
Thank you for consistent updates and photos @AArman986. I believe that I have resolved the issue now. I had to switch the build properties from "debug" to "release". I was able to test this on another computer and it seems to be working for me.

Let me know if you have any trouble.

**Comment by AArman986** [comment]
Hi, thanks retug. Unfortunately after downloading the updated dll, I still get the same error. I am assuming that all the files I placed in the plugin folder are correct and it does not matter the location. Is there any other prerequisite software required for this to work that a non programming user may have to install?
![image](https://github.com/retug/SectionCutter/assets/158470435/b98f799b-dae6-476b-9257-757f0699cc8b)

**Comment by retug** [comment]
I should have started with this question, what version of ETABs are you running? 
I have it running on the current version 21. I believe the addin should work on version 20 and 21, but will not work on version 19 and below. 

I will post a screenshot of my current application folder when I get home later today. I only have sectioncutter.dll, livecharts.wpf.dll and livecharts.winforms.dll in my referenced application folder I believe.

**Comment by AArman986** [comment]
I am running ETABS v21.2.0. I placed the folder in my documents

**Comment by retug** [comment]
I will put together a youtube video showing the steps that I took later today. If that doesn't solve it, maybe a quick screenshare in the future if you are willing.

**Comment by AArman986** [comment]
OK. Thanks.

**Comment by retug** [comment]
https://youtu.be/CUDt8zJYAoc, try this video. I added a new zip file as well under .dll in github.

**Comment by AArman986** [comment]
Hi, thanks, that seemed to work. Initially when I added the plugin (with the new files from zip) it said plugin failed but I just saved the file, closed etabs and reopened and it worked. Can you post a video how to use it.

I see that you did a plugin for ram to revit, and was wondering if you are able to create a plugin which can export ETABS forces to ram connection since you seem to be familiar with the two software. Thanks for everything.

**Comment by retug** [comment]
Great! Awesome news that it works now. Again, apologies for all the install trouble. I will plan on creating a video on how to use in the future.

"I see that you did a plugin for ram to revit, and was wondering if you are able to create a plugin which can export ETABS forces to ram connection since you seem to be familiar with the two software"

I would give this a solid maybe. I have not worked a ton with ram connection, but there is the possibility that we could get it to programmatically interact with other data if there is an API exposed by RAM. I would say shoot me a direct message to discuss what workflow you are looking to achieve and I can take it from there. You can find my email on my website, re-tug.com. Pulling out the ETABs forces should be no problem, just not sure on the ram connection side.

Thanks!

**Comment by retug** [comment]
How to use video. https://www.youtube.com/watch?v=L_XXPHafNQQ
