### ISSUE TITLE
allow processing of multiple steps in load case

### ISSUE THREAD

**Issue by jlinfordREA** [retug/SectionCutter#8]
thinking of multiple eccentric load cases in particular. Plot all steps as overlay on plot and maybe include an envelope one as well.

**Comment by retug** [comment]
Thanks @jlinfordREA . I have a question into CSI outlining some of the issues I am running into with the API regarding autoseismic and autowind  steps.

https://www.eng-tips.com/viewthread.cfm?qid=516549

**Comment by retug** [comment]
![image](https://github.com/retug/SectionCutter/assets/45467091/3cc1d48d-174b-4ea6-8ee4-cebc03e3606b)
making progress

**Comment by retug** [comment]
Full Functionality added for ASCE 7-16 and ASCE 7-22 load patterns.
