### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by jchatkinson** [retug/SectionCutter#9]
Hi Austin, thanks for publishing the code for this. Its a useful reference and cool tool. 

I just wanted to note some issues I had getting this to compile and load into etabs 21 in case others run into the same problem:

- I couldn't just reference the SectionCutter.dll file in ETABS, it needs to include the other files that come from the \bin\Release folder. 
- Visual Studio seemed to have a problem with the references. I had to uninstall and reinstall the MathNet and LiveCharts packages.
- Had to delete an autogenerated AssemblyInfo.cs file to build. 

some of this might be due to my setup. 

Cheers
JA

**Comment by retug** [comment]
Just updated some of the install instruction. Give it a try and see if this works now. 
Thanks for testing it out.

**Comment by retug** [comment]
Hopefully resolved now. See youtube here, https://www.youtube.com/watch?v=CUDt8zJYAoc

**Comment by retug** [comment]
complete
